### ISSUE TITLE
document whitelisting IPv6 blocks

### ISSUE THREAD

**Issue by MarcusWolschon** [mawis/couriergrey#2]
There is no example or documentation on how to add an IPv6 subnet into /etc/couriergrey/whitelist_ip
Just entering a ":" separated subnet like in the IPv4 subnets results in ridiculus entriey like
::ffff:2607:f8b0:400d:c09/128

**Comment by mawis** [comment]
Have you tried the syntax documented in whitelist_ip.dist?

Just adding the begin of a IPv4 address is only considered to by a legacy syntax. The preferred syntax to add networks is to write a complete IP address, followed by a slash and the network size.

> Couriergrey should fully support the format used there, but has some
> extensions to the format, to support class-less routing and IPv6 addresses.
> 
> Due to the extensions, the following entries can be written as well:
> 
> 192.168.0.0/16 # for all addresses from 192.168.0.0 to 192.168.255.255
> 172.16.0.0/12 # for addresses in the class B private network addresses
> 2001:12ab::/32 # for an IPv6 network
> ::ffff:192.168.0.0/112 # it is also valid to use mapped IPv4 addresses

**Comment by MarcusWolschon** [comment]
My previously unmodified whitelist_ip file in Debian did not include this IPv6 example.

**Comment by mawis** [comment]
I think I can consider this as done.

**Comment by MarcusWolschon** [comment]
Where was it added in /usr/share/doc ?

**Comment by mawis** [comment]
Here in the upstream repository of couriergrey it is present in `whitelist_ip` since the beginning. If you think the file is incorrect in the Debian package, you should report it to https://bugs.debian.org/cgi-bin/pkgreport.cgi?dist=unstable;package=couriergrey

This can be done with the `reportbug` tool: https://www.debian.org/Bugs/Reporting

**Comment by mawis** [comment]
I try to figure out more and just contacted the Debian package maintainer.

**Comment by MarcusWolschon** [comment]
I don't think examples in an initial config file are the same as documentation.
Examples are gone after the user has written the config for the first time
but documentation should still be around when needing to change that years later.
Permanent and comprehensive documentation belongs in /usr/share/doc or man-pages.

**Comment by mawis** [comment]
I think this is a good idea to write some documentation for that. I'd love to get a PR for this.
